### ISSUE TITLE
other: 新混淆工具

### ISSUE THREAD

**Issue by goodwenhao** [echo094/decode-js#112]
### Which plugin are you reporting a bug for?

obfuscator

### Version of Node

20.14

### Input code

https://github.com/goodwenhao/study/blob/main/test.js

**Comment by echo094** [comment]
这个样本并不是obfuscator，是一种全新的混淆方式，简单分析了一下供你参考。

这种混淆方式的核心内容是头尾的两部分代码：

```js
// 头部
function ggsElv() {}
PS61TpK = Object["defineProperty"]
function b2YUfe(ggsElv) {
  return x_bH3Yz[ggsElv < 48 ? ggsElv - 94 : ggsElv > 281 ? ggsElv - 80 : ggsElv - 49];
}
x_bH3Yz = UehMhMQ.call(this);
function nS3LeN(ggsElv, PS61TpK) {
  GrpZibt(ggsElv, "length", {
    value: PS61TpK,
    configurable: b2YUfe(104)
  });
  return ggsElv;
}
GrpZibt = Object.defineProperty;
var XPU2Of = [], MrnEyjO = [...]

// 尾部
function UehMhMQ() {
  return [...];
}
function JBApsSj(ggsElv, x_bH3Yz = 0) {
  var GrpZibt = function () {
    return ggsElv(...arguments);
  };
  return PS61TpK(GrpZibt, "length", {
    "value": x_bH3Yz,
    "configurable": true
  });
}
```

- 空函数`ggsElv`的作用是执行参数语句，能够打乱代码块的逻辑
- 列表`MrnEyjO`和`UehMhMQ`收集了部分字符串和数值（obfuscator的列表只收集字符串）
- （第一种嵌套）函数`b2YUfe`间接调用列表`UehMhMQ`（第一种嵌套）
- （第二种嵌套）函数`nS3LeN`和`JBApsSj`用来包装参数`ggsElv`，并返回一个函数（核心仍是`ggsElv`）

**Comment by goodwenhao** [comment]
好的，目前该项目解不了这种新型的是吧

**Comment by echo094** [comment]
如果这是一种公开的混淆工具，可以考虑添加

**Comment by goodwenhao** [comment]
okk期待佬适配

**Comment by echo094** [comment]
> 我近期也发现了这类加密的不断出现

所以你知道这个工具的链接吗

**Comment by Tlaeld** [comment]
新混淆工具，求佬支持：
https://github.com/MichaelXF/js-confuser

**Comment by echo094** [comment]
适配中，不定时更新到分支 [jsconfuser](https://github.com/echo094/decode-js/tree/jsconfuser)

**Comment by greenwave1987** [comment]
现在能解吗？我这报错还是不行。

**Comment by echo094** [comment]
> 现在能解吗？我这报错还是不行。

你可以把你的样本贴出来。

**Comment by greenwave1987** [comment]
https://raw.githubusercontent.com/6dylan6/jdpro/refs/heads/main/jd_dpqd_sign.js这个解一半报错。

**Comment by wangjing71** [comment]
部分脚本报错。

**Comment by lolkda** [comment]
[StringConcealing] getter: JIavgun decoder: MRhvx7H
[StringConcealing] getter: bXiulmK decoder: Om_FdG
Process Function WE5lUG, len: 2
Process Function xctJAB, len: 1
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 0
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 1
Process Function bdUTycT, len: 2
Process arrowFunctionExpression, len: 1
Process arrowFunctionExpression, len: 0
[OpaquePredicates] predicateName : z7z2W9
D:\Personal\Desktop\decode-js-jsconfuser\src\plugin\jsconfuser.js:1459
      const res = vm.evalSync(test)
                     ^

ReferenceError: _lJcoP is not defined
    at <isolated-vm>:1:16
    at (<isolated-vm boundary>)
    at ObjectExpression (D:\Personal\Desktop\decode-js-jsconfuser\src\plugin\jsconfuser.js:1459:22)
    at _call (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:49:20)
    at call (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:39:18)
    at visit (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:85:31)
    at visitQueue (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:89:16)
    at visitSingle (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:65:19)
    at visit (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at visit (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at visitQueue (D:\Personal\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:89:16)

Node.js v20.9.0

**Comment by iiiiqt** [comment]
大部分脚本报错。

**Comment by Tlaeld** [comment]
https://github.com/6dylan6/jdpro/blob/main/function/dylano.js
https://github.com/6dylan6/jdpro/blob/main/function/dylans.js
https://github.com/6dylan6/jdpro/blob/main/function/dylanv.js
https://github.com/6dylan6/jdpro/blob/main/function/dylanw.js

以上js都反混淆报错，大佬求更新

**Comment by wangjing71** [comment]
TypeError: Cannot read properties of undefined (reading 'constantViolations')
    at StringLiteral (C:\Users\hp\Desktop\decode-js-jsconfuser\src\plugin\jsconfuser.js:1283:17)
    at NodePath._call (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:49:20)
    at NodePath.call (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:39:18)
    at NodePath.visit (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:85:31)
    at TraversalContext.visitQueue (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\hp\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:89:16)

**Comment by echo094** [comment]
这个混淆工具剩下的几个流程比较复杂，最近有很多别等事，这个月没有足够的时间用来分析和编码，等空下来再看。

**Comment by wangjing71** [comment]
好像还是解不了、。。

**Comment by echo094** [comment]
> 好像还是解不了、。。

这里面，Stack混淆比较难搞。

**Comment by YouDianWeiLing** [comment]
> > 好像还是解不了、。。
> 
> 这里面，Stack混淆比较难搞。

 大佬这种报错是node版本不对吗？
StringConcealing] getter: ogHyqDw decoder: OlbW9t
[Stack] Process Function BpLlTb, len: 2
[Stack] Process Function SY7zUs6, len: 1
[Stack] Process arrowFunctionExpression, len: 1
[Stack] Process arrowFunctionExpression, len: 0
[Stack] Process arrowFunctionExpression, len: 1
[Stack] Process Function AKHxV8y, len: 0
[Stack] Process Function KwJlQoy, len: 2
[Stack] Process arrowFunctionExpression, len: 3
[Stack] Process arrowFunctionExpression, len: 3
[Stack] Process arrowFunctionExpression, len: 3
[Stack] Process arrowFunctionExpression, len: 3
[OpaquePredicates] predicateName : cytOMh
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ReferenceError: brSc5ZL is not defined
    at <isolated-vm>:1:15
    at (<isolated-vm boundary>)
    at ObjectExpression (file:///C:/Users/lb/Desktop/decode-js-jsconfuser/src/visitor/jsconfuser/opaque-predicates.js:149:22)
    at _call (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:49:20)
    at call (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:39:18)
    at visit (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:85:31)
    at visitQueue (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:89:16)
    at visitSingle (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:65:19)
    at visit (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at visit (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at visitQueue (C:\Users\lb\Desktop\decode-js-jsconfuser\node_modules\@babel\traverse\lib\context.js:89:16)

Node.js v18.18.2

**Comment by echo094** [comment]
有些属于Stack的混淆没有被处理干净，遗留到后续流程了，正在想办法
