### ISSUE TITLE
解密报错了

### ISSUE THREAD

**Issue by Huanting93** [echo094/decode-js#2]
[qm.txt](https://github.com/echo094/decode-js/files/11038768/qm.txt)
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
ReferenceError [Error]: _0x10eeb0 is not defined
    at vm.js:1:1
    at Script.runInContext (node:vm:141:12)
    at VM.runScript (E:\decode-js-main\node_modules\vm2\lib\vm.js:285:18)
    at VM.run (E:\decode-js-main\node_modules\vm2\lib\vm.js:503:16)
    at virtualGlobalEval (file:///E:/decode-js-main/src/plugin/obfuscator.js:22:14)
    at decodeGlobal (file:///E:/decode-js-main/src/plugin/obfuscator.js:134:3)
    at default (file:///E:/decode-js-main/src/plugin/obfuscator.js:1076:3)
    at file:///E:/decode-js-main/src/main.js:35:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)

三种方式都报错了，求适配

**Comment by echo094** [comment]
这是一个由obfuscator混淆的脚本，但是在特征中缺少了sort函数，导致现有的插件无法正确定位主加密函数。

这个脚本使用了class类型，这是在ES6添加的特性，类成员函数在混淆后（以及解密后）的形式有些奇特。

现已适配该样本，如果仍有问题可以重新打开本issue；如有别的问题，可以提新的issue。

**Comment by Huanting93** [comment]
> 这是一个由obfuscator混淆的脚本，但是在特征中缺少了sort函数，导致现有的插件无法正确定位主加密函数。
> 
> 这个脚本使用了class类型，这是在ES6添加的特性，类成员函数在混淆后（以及解密后）的形式有些奇特。
> 
> 现已适配该样本，如果仍有问题可以重新打开本issue;如有别的问题，可以提新的issue。

好的，感谢适配。
