### ISSUE TITLE
obfuscator类解密失败

### ISSUE THREAD

**Issue by TongLin138** [echo094/decode-js#31]
链接：https://playcode.io/1572594
具体代码以及报错内容全部放在链接中。

**Comment by echo094** [comment]
> 链接：https://playcode.io/1572594 具体代码以及报错内容全部放在链接中。

这个混淆方法有两处改进：

1. 字符串表排序函数传入了2个变量（以前只有字符串表自身）
2. 在上面等第2个变量中添加了防格式化校验，如果在早期格式化会直接卡死。

我先想想怎么把1中的另一个变量找到。

**Comment by hetoo** [comment]
刚才解析碰到一个错误

file:///E:/decode-js/src/plugin/obfuscator.js:564
    if (!up1.scope.bindings[child].constant) {
                                   ^

TypeError: Cannot read properties of undefined (reading 'constant')
    at mergeObject (file:///E:/decode-js/src/plugin/obfuscator.js:564:36)
    at NodePath._call (E:\decode-js\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (E:\decode-js\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at TraversalContext.visitQueue (E:\decode-js\node_modules\@babel\traverse\lib\context.js:103:16)
    at TraversalContext.visitMultiple (E:\decode-js\node_modules\@babel\traverse\lib\context.js:72:17)
    at TraversalContext.visit (E:\decode-js\node_modules\@babel\traverse\lib\context.js:129:19)
    at traverseNode (E:\decode-js\node_modules\@babel\traverse\lib\traverse-node.js:24:17)
    at NodePath.visit (E:\decode-js\node_modules\@babel\traverse\lib\path\context.js:107:52)
    at TraversalContext.visitQueue (E:\decode-js\node_modules\@babel\traverse\lib\context.js:103:16)

**Comment by cesaryuan** [comment]
> 这个代码缺依赖项，我这没法测试能不能运行，如果还有问题就继续贴在下面

测试了下还是有同样的错误：https://playcode.io/1573867
```
类型: obfuscator
输入: input.js
输出: output.js
还原数值...
处理全局加密...
String List Name: a0_0x4787

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
ReferenceError [Error]: a0_0x3a06 is not defined
    at vm.js:1:15
    at Script.runInContext (node:vm:141:12)
    at VM.runScript (E:\04Code\JS\decode-js\node_modules\vm2\lib\vm.js:285:18)
    at VM.run (E:\04Code\JS\decode-js\node_modules\vm2\lib\vm.js:503:16)
    at virtualGlobalEval (file:///E:/04Code/JS/decode-js/src/plugin/obfuscator.js:22:14)
    at decodeGlobal (file:///E:/04Code/JS/decode-js/src/plugin/obfuscator.js:414:5)
    at default (file:///E:/04Code/JS/decode-js/src/plugin/obfuscator.js:1240:3)
    at file:///E:/04Code/JS/decode-js/src/main.js:36:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

**Comment by echo094** [comment]
> 刚才解析碰到一个错误
> 

可以贴个代码

**Comment by echo094** [comment]
> 测试了下还是有同样的错误：https://playcode.io/1573867
> 

更新了，再试一下。

这几个账号都是你的吗，不新开帖子会打扰别人。

**Comment by hetoo** [comment]
> > 刚才解析碰到一个错误
> 
> 可以贴个代码

https://raw.githubusercontent.com/6dylan6/jdpro/main/function/dylany.js

**Comment by echo094** [comment]
> https://raw.githubusercontent.com/6dylan6/jdpro/main/function/dylany.js

更新了，确实是BUG，删除未使用变量后忘了更新作用域。

**Comment by TongLin138** [comment]
> 链接：https://playcode.io/1572594 具体代码以及报错内容全部放在链接中。

链接中放入了script2.js 和输出结果.js。尽管显示成功净化，但代码还是混淆状态。不知道和script.js是不是相同原因，所以放在一个issue中。

上面的GitHub账户不是我的。

**Comment by echo094** [comment]
> 链接中放入了script2.js 和输出结果.js。尽管显示成功净化，但代码还是混淆状态。不知道和script.js是不是相同原因，所以放在一个issue中。

实际上并没有，显示错误已经改了。

这个脚本将混淆参数降低了，导致没有了排序函数，我还是第一次见到这种配置。

更新了，你试试吧。

**Comment by TongLin138** [comment]
问题已解决，感谢。
