### ISSUE TITLE
sojsonv7错误

### ISSUE THREAD

**Issue by knowledgeablelmh** [echo094/decode-js#63]
PS C:\Users\Admin\Desktop\decode-js-main> node src/main.js -t sojsonv7
类型: sojsonv7
输入: input.js
输出: output.js
处理全局加密...
Version var: _0xodE
Unexpected ref var_version: _0xodE = 17741
Main call wrapper name: _0x2b5e
Go to sub: _0x2dc653
Go to sub: _0x483557
Go to sub: _0x44625f

C:\Users\Admin\Desktop\decode-js-main\node_modules\vm2\lib\vm.js:290
                                throw bridge.from(e);
                                ^
URIError [Error]: URI malformed
    at decodeURIComponent (<anonymous>)
    at _0x2b5ea7 (vm.js:1:29525)
    at Function._0x338e80 [as aUtUyx] (vm.js:1:29665)
    at _0x2b5e (vm.js:1:31584)
    at _0x2b5e (vm.js:1:31682)
    at vm.js:1:1
    at Script.runInContext (node:vm:134:12)
    at VM.runScript (C:\Users\Admin\Desktop\decode-js-main\node_modules\vm2\lib\vm.js:288:18)
    at VM.run (C:\Users\Admin\Desktop\decode-js-main\node_modules\vm2\lib\vm.js:508:16)
    at virtualGlobalEval (C:\Users\Admin\Desktop\decode-js-main\src\plugin\sojsonv7.js:18:14)

Node.js v20.9.0

https://note.ms/ddyc

这是代码

**Comment by echo094** [comment]
同#62 近期修复
