### ISSUE TITLE
dependency: ReferenceError: Container is falsy

### ISSUE THREAD

**Issue by To-King** [echo094/decode-js#86]
D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\replacement.js:164
    throw new ReferenceError("Container is falsy");
    ^

ReferenceError: Container is falsy
    at NodePath._replaceWith (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\replacement.js:164:11)
    at NodePath._remove (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\removal.js:59:10)
    at NodePath.remove (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\removal.js:38:8)
    at hooks (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\lib\removal-hooks.js:11:12)
    at NodePath._callRemovalHooks (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\removal.js:50:9)
    at NodePath.remove (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\removal.js:30:12)
    at mergeObject (D:\工具\decode-js-main\src\plugin\obfuscator.js:635:9)
    at NodePath._call (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\工具\decode-js-main\node_modules\@babel\traverse\lib\path\context.js:109:8)

Node.js v18.18.0

**Comment by echo094** [comment]
有没有能够复现的简单样本

**Comment by echo094** [comment]
参考 #92 可以尝试更新下npm依赖
